/**
 * Hourly nudge job, moved from index.js.
 *
 * Offers a Pro trial to lite-tier users who spoke 20-23 hours ago and have never
 * been nudged. The window is deliberately narrow so a user is offered this once.
 *
 * GENERATED by scripts/extract-legacy.cjs.
 */

const cron = require('node-cron');
const { pool } = require('../db/pool');
const { logger } = require('../lib/logger');
const events = require('../services/events');
const { twilioClient } = require('../legacy/concierge');

const SOVEREIGN_NUDGE_MESSAGE = `Architect here. I've been monitoring your request. I have a predictive strategy ready that would offload these logistics entirely. Would you like to activate a 30-day free trial of the Pro Vault to see the difference? Reply 'YES' to begin.`;

/** Register the schedule. Called once from server.js. */
function start() {
  if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_WHATSAPP_FROM) {
    logger.warn('cron.nudge_disabled', { reason: 'twilio not configured' });
    return null;
  }
  const schedule = process.env.NUDGE_CRON_SCHEDULE || '0 * * * *';
  logger.info('cron.nudge_started', { schedule });
  
  cron.schedule(process.env.NUDGE_CRON_SCHEDULE || '0 * * * *', async () => {
    if (!twilioClient || !process.env.TWILIO_WHATSAPP_FROM) {
      return;
    }
    try {
      const { rows } = await pool.query(
        `SELECT u.id, u.phone_number, u.first_name
         FROM users u
         INNER JOIN (
           SELECT user_id, MAX(timestamp) AS last_ts
           FROM conversations
           GROUP BY user_id
         ) last ON last.user_id = u.id
         WHERE u.tier = 'lite'
           AND u.last_nudge_at IS NULL
           AND last.last_ts >= NOW() - INTERVAL '23 hours'
           AND last.last_ts <= NOW() - INTERVAL '20 hours'`
      );
      for (const user of rows) {
        const to = user.phone_number.startsWith('whatsapp:') ? user.phone_number : `whatsapp:${user.phone_number}`;
        await twilioClient.messages.create({
          body: SOVEREIGN_NUDGE_MESSAGE,
          from: process.env.TWILIO_WHATSAPP_FROM,
          to,
        });
        await pool.query('UPDATE users SET last_nudge_at = NOW() WHERE id = $1', [user.id]);
        console.log('Nudge sent to', user.phone_number);
      }
    } catch (err) {
      console.error('Nudge cron failed:', err.message);
    }
  });
  return true;
}

module.exports = { start };
