/**
 * One-shot extraction of the agent internals out of index.js.
 *
 * The concierge brain (prompts, Anthropic tool wiring, Airtable/Pipedream
 * helpers) is moved VERBATIM into src/legacy/concierge.js. It is not rewritten:
 * rewriting 1,700 lines of prompt-coupled logic in the same change as the
 * restructure would make any regression impossible to attribute.
 *
 * Idempotent. Re-running regenerates the output files from index.js.
 *
 *   node scripts/extract-legacy.cjs
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const lines = fs.readFileSync(path.join(ROOT, 'index.js'), 'utf8').split('\n');

/** 1-indexed inclusive slice, matching what the editor and grep report. */
const slice = (from, to) => lines.slice(from - 1, to).join('\n');

// Boundaries, verified against index.js before extraction:
//     1-28    requires and client construction
//    29-85    Stripe webhook route
//    86-98    express setup, pg pool, nanoid
//   99-1833   helpers and agent internals      -> concierge.js
// 1834-1867   nudge cron                        -> jobs/nudge.js
// 1868-2389   more helpers, agent, constants    -> concierge.js
// 2390-2584   Twilio webhook route
// 2585-2774   landing page route
// 2775-2795   health route and server boot
const BRAIN_A = [99, 1833];
const CRON = [1834, 1867];
const BRAIN_B = [1868, 2389];

const HEADER = `/**
 * Legacy concierge internals, moved verbatim from index.js.
 *
 * GENERATED by scripts/extract-legacy.cjs. Edit the logic here from now on;
 * index.js is no longer the source of truth.
 *
 * This file is a staging post, not a destination. It holds the agent brain as
 * it was so the restructure could land without changing behaviour. The pieces
 * belong in src/services/ (onboarding, calendar, architecture) and should be
 * moved out one at a time, each with a test.
 *
 * New code should prefer src/services/* and src/integrations/*, which are
 * tested and carry request-scoped logging.
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk');
const Composio = require('@composio/client');
const { GoogleGenAI } = require('@google/genai');
const { tavily } = require('@tavily/core');
const nodemailer = require('nodemailer');
const twilio = require('twilio');
const { customAlphabet } = require('nanoid');

// The shared pool, so this module does not open a second one.
const { pool } = require('../db/pool');

// This file sits at src/legacy/, so __dirname no longer points at the project
// root. skills/ and init-db.sql are still resolved relative to the root.
const PROJECT_ROOT = path.join(__dirname, '..', '..');

const tavilyClient = process.env.TAVILY_API_KEY ? tavily({ apiKey: process.env.TAVILY_API_KEY }) : null;
const twilioClient =
  process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN
    ? twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)
    : null;

const generateAiShortIdBody = customAlphabet(
  '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
  9
);

// ---------------------------------------------------------------------------
// Moved verbatim from index.js below this line.
// ---------------------------------------------------------------------------
`;

let body = `${slice(...BRAIN_A)}\n${slice(...BRAIN_B)}`;

// --- Fixes applied during the move -----------------------------------------

// The code now lives two directories down, so __dirname no longer resolves to
// the project root. skills/ and init-db.sql are still at the root.
body = body.replace(/path\.join\(__dirname,/g, 'path.join(PROJECT_ROOT,');

// getUserByPhone and createNewUser both use a hand-written column list. The MVP
// columns are appended so the user object the webhook receives actually carries
// them — without this, user.conversation_mode is undefined and the human
// hand-off gate silently never fires.
body = body.replaceAll(
  'architecture_synced_at, onboarding_status, onboarding_step, active_automations, preferences',
  'architecture_synced_at, onboarding_status, onboarding_step, active_automations, preferences, '
    + 'conversation_mode, onboarding_phase, onboarding_completed_at, last_date_curated_at, '
    + 'date_night_cadence, next_date_due_at'
);

// Pre-existing bug, fixed here rather than carried forward:
//   new GoogleGenAI(process.env.GEMINI_API_KEY)
// The SDK takes an options object, not a bare string. Passing a string happens
// to survive when the key is set, but with GEMINI_API_KEY unset it is called
// with `undefined` and throws at require-time, taking the whole process down
// before the server can listen. Guarded like every other optional client.
body = body.replace(
  'const googleAI = new GoogleGenAI(process.env.GEMINI_API_KEY);',
  'const googleAI = process.env.GEMINI_API_KEY\n'
    + '  ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })\n'
    + '  : null;'
);

// Export every top-level declaration rather than curating a list: this is a
// compatibility layer, and an omission here is a runtime crash in the webhook.
const names = new Set();
for (const m of body.matchAll(/^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/gm)) names.add(m[1]);
for (const m of body.matchAll(/^const\s+([A-Z][A-Z0-9_]*)\s*=/gm)) names.add(m[1]);

const sorted = [...names].sort();
const footer = `

// ---------------------------------------------------------------------------
module.exports = {
  pool,
  tavilyClient,
  twilioClient,
${sorted.map((n) => `  ${n},`).join('\n')}
};
`;

fs.mkdirSync(path.join(ROOT, 'src', 'legacy'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'src', 'legacy', 'concierge.js'), HEADER + body + footer);

const NUDGE = `/**
 * Hourly nudge job, moved from index.js.
 *
 * Offers a Pro trial to lite-tier users who spoke 20-23 hours ago and have never
 * been nudged. The window is deliberately narrow so a user is offered this once.
 *
 * GENERATED by scripts/extract-legacy.cjs.
 */

const cron = require('node-cron');
const { pool } = require('../db/pool');
const { logger } = require('../lib/logger');
const events = require('../services/events');
const { twilioClient } = require('../legacy/concierge');

${slice(CRON[0], CRON[0])}

/** Register the schedule. Called once from server.js. */
function start() {
  if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_WHATSAPP_FROM) {
    logger.warn('cron.nudge_disabled', { reason: 'twilio not configured' });
    return null;
  }
  const schedule = process.env.NUDGE_CRON_SCHEDULE || '0 * * * *';
  logger.info('cron.nudge_started', { schedule });
${slice(CRON[0], CRON[1])
  .split('\n')
  .slice(1)
  .map((l) => '  ' + l)
  .join('\n')
  .replace(/\n {2}\}\);\s*$/, '\n  });')}
  return true;
}

module.exports = { start };
`;

fs.mkdirSync(path.join(ROOT, 'src', 'jobs'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'src', 'jobs', 'nudge.js'), NUDGE);

console.log(`concierge.js : ${body.split('\n').length} lines, ${sorted.length} exports`);
console.log(`nudge.js     : written`);
